### DISCUSSION TITLE
Screen lock status (sway wm)

### DISCUSSION THREAD

**Discussion by Ramblurr** [tobias-kuendig/hacompanion#23] [Show and tell]
Here's a simple custom script to create a `screen_lock_status` entity for your computer, if you're running the [sway tiling window manager](https://swaywm.org/). It can easily be adapted to other screen lockers.

```bash
#!/bin/bash

pidof swaylock &> /dev/null
rc="$?"

if [[ "$rc" == "0" ]]; then
  echo "locked"
  echo "icon:mdi:lock"
else
  echo "unlocked"
  echo "icon:mdi:lock-open"
fi
```

The hacompanion config: 
```toml
[script.locked_status]
path = "/home/user/.local/bin/swaylock-status"
name = "screen_lock_status"
icon = "mdi:lock"
type = "sensor"
```
