### DISCUSSION TITLE
Screen lock status (loginctl)

### DISCUSSION THREAD

**Discussion by MasonRhodesDev** [tobias-kuendig/hacompanion#28] [Show and tell]
A custom screen lock sensor implemented using the `loginctl` utility.

It checks for _at least_ 1 unlocked GUI session in either wayland or X11.

is_locked.sh
``` bash
#!/bin/bash

SESSIONS=$(loginctl list-sessions | awk '/SESSION/ {next} {print $1}' | sed '$d')

value=0
for sessionId in $SESSIONS
do
        # check if session is X11 or Wayland
        sessionType=$(loginctl show-session $sessionId -p Type | cut -d= -f2)
        if [ "$sessionType" = "x11" ] || [ "$sessionType" = "wayland" ];
        then
                # check if session is locked
                if [ $(loginctl show-session $sessionId -p LockedHint | cut -d= -f2) = "yes" ];
                then
                        value=1
                        break
                fi
        fi
done

if [ $value -eq 1 ];
then
        echo "true"
        echo "icon:mdi:lock-outline"
else
        echo "false"
        echo "icon:mdi:lock-open-outline"
fi
```

Config block
``` toml
[script.is_locked]
path = "/home/user/.config/hacompanion/scripts/is_locked.sh" # or wherever you put it
name = "Is Locked"
icon = "mdi:lock-outline"
type = "binary_sensor"
```
