### DISCUSSION TITLE
Alternative webcam check (lsof)

### DISCUSSION THREAD

**Discussion by MasonRhodesDev** [tobias-kuendig/hacompanion#29] [Show and tell]
I was getting some false positives with the built-in webcam checker and I ended up wanting a little more information about what process was using the device anyways.

This version also includes the pids, users, and commands that are accessing the given device.
In my case `/dev/video0`

webcam_in_use.sh
``` bash
#!/bin/bash

# Run lsof to get the output stream
lsof_output=$(lsof /dev/video0 2>/dev/null)

# Check if lsof encountered an error (device unplugged)
if [[ $? -ne 0 ]]; then
    echo "false"
    echo "pids:"
    echo "commands:"
    echo "users:"
    echo "icon:mdi:camera-off"
    exit 0
fi

# Process the lsof output and format as JSON objects
previous_pid=""

PIDS=""
COMMANDS=""
USERS=""

while read -r line; do
  if [[ $line =~ ^COMMAND.* ]]; then
    # Skip the header line
    continue
  else
    # Process the fields of lsof output
    read -r command pid user _ _ _ _ _ _ _ <<<"$line"

    # ignore the entry if the pid is the same as the previous one
    if [[ "$pid" != "$previous_pid" ]]; then
      PIDS="$PIDS $pid"
      COMMANDS="$COMMANDS $command"
      USERS="$USERS $user"
    fi
  fi
done <<<"$lsof_output"

echo "true"
echo "pids:$PIDS"
echo "commands:$COMMANDS"
echo "users:$USERS"
echo "icon:mdi:camera"
exit 0
```

Config block
``` toml
[script.webcam_in_use]
path = "/home/user/.config/hacompanion/scripts/webcam_in_use.sh"
name = "Webcam In Use"
icon = "icon:mdi:camera"
type = "binary_sensor"
```
