### DISCUSSION TITLE
Can we have electricity consumption?

### DISCUSSION THREAD

**Discussion by G-D-D-971** [tobias-kuendig/hacompanion#43] [Q&A]
Hello, I am looking for a way to obtain the power consumption of the computer, it would be convenient to have a precise idea of the energy impact of the computer. If someone has already made a script or if it is not possible...

Thank you in advance for your answers.

**Comment by ensonic** [comment]
I am experimenting with using https://www.linux.org/docs/man8/turbostat.html (for the CPU). Similarly we can probably get data from gpu and maybe fans. In any case using a powerplug that can measure in a black box fashion is probably the easier way.

It would be nice to natively integrate is as the current power report seems to only works for battery powered devices and is actually the battery level :)

my script:
```shell
sudo /usr/bin/turbostat --Summary --quiet --show PkgWatt --num_iterations 1 | tail -1
```

I've also created `/etc/sudoers.d/hacompanion` with (replace `you` with your username)
```
you ALL = (ALL) ALL
you ALL = (root) NOPASSWD: /usr/bin/turbostat
```
That let's you run turbostat with sudo without entering a password. The turbostate man page offers alternatives.

And the hacompanion block (again replace `you`):
```toml
[script.cpu_power]
path = "/home/you/bin/hacompanion_power.sh"
name = "CPU power usage"
icon = "mdi:flash"
type = "sensor"
unit_of_measurement = "W"
device_class = "power"
```
(If we could use e.g $HOME that'd be nice to make things more portable.)
