### ISSUE TITLE
shouldn't script sensors can use path = "~/bin/myscript.sh"

### ISSUE THREAD

**Issue by ensonic** [tobias-kuendig/hacompanion#52]
https://github.com/tobias-kuendig/hacompanion/blob/main/main.go#L408-L430 implemenets a path resolver, but if I use:
```toml
[script.cpu_power]
path = "~/bin/hacompanion_power.sh"
name = "CPU power usage"
icon = "mdi:flash"
type = "sensor"
unit_of_measurement = "W"
device_class = "power"
```

I get `failed to run sensor CPU power usage (cpu_power): fork/exec ~/bin/hacompanion_power.sh: no such file or directory`. With the abs path it works. I'll check the code a bit more closely in the next days.
